### ISSUE TITLE
PHP server is constantly crashing

### ISSUE THREAD

**Issue by TitanNano** [php-integrator/core#57] opened 2016-12-21 10:15 UTC
The PHP server is constantly crashing when trying to re index my php source after I saved a file. 
There seems also not to be any attempt to restart the server so I'm constantly forced to restart Atom 😕

![screen shot 2016-12-21 at 11 10 07](https://cloud.githubusercontent.com/assets/4500858/21385363/7c8abf3e-c76e-11e6-933a-248356dee591.png)

**Comment by Gert-dev** [comment] 2016-12-21 12:07
Hello, this is a duplicate of [this ticket](https://github.com/php-integrator/atom-base/issues/259).

**Closed by Gert-dev** 2016-12-21 12:07 UTC
