### ISSUE TITLE
define() Parsing fails with object accessor in double-quote string interpolation

### ISSUE THREAD

**Issue by GiacoCorsiglia** [php-integrator/core#83] opened 2017-02-01 21:00 UTC
I had a similar problem to #82 whereby php-integrator indexing would stop midway without issuing errors.  2.1.3's newly thrown errors for default value parsing have revealed the problem:  It seems that parsing fails on statements of the form `define( 'NAME', "{$obj->prop}" )`.

I'm working on WordPress project, so the line in context is [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/ms-default-constants.php#L36) (and on [line 40](https://github.com/WordPress/WordPress/blob/master/wp-includes/ms-default-constants.php#L40)).  I messed with it a little bit to try to isolate the problem:

- (original) Fails: `define( 'UPLOADS', UPLOADBLOGSDIR . "/{$wpdb->blogid}/files/" );`
- Works: `define( 'UPLOADS', UPLOADBLOGSDIR . "/{$wpdb}/files/" );`
- Fails: `define( 'UPLOADS', "/{$wpdb->blogid}/files/" );`
- Fails: `define( 'UPLOADS', "{$wpdb->blogid}" );`
- Works: `define( 'UPLOADS', $wpdb->blogid );`

(Note when it "works" it still fails on line 40 of course.)

I just discovered this project last night and it's fantastic.  The mysterious incomplete indexing was a bummer but I was able to work around it—and lo, the very next day a partial fix is out.  Thanks for your efforts!  Please let me know if I can provide more information on this issue.

**Comment by Talv** [comment] 2017-02-02 03:20
Nice timing with the related fix. Yesterday I was doing some digging on the same exact problem, and meant to post info today, but it's already resolved, haha. Maybe not this specific one though, but atleast leaked parsing exceptions are no longer silently aborting indexing process. :+1:

As for this specific case, the ```PartialParser::getStartOfExpression``` fails to walk through strings with embedded expressions via curly syntax, which contain more than a single variable.
Here is where things go wrong:
https://github.com/php-integrator/core/blob/44676d077b4f7d9ec665334ab69df245b8489efa/src/Parsing/PartialParser.php#L196
It's not aware that ```}``` is inside a string literal, as it solely rely on single  ```T_CONSTANT_ENCAPSED_STRING``` token for detecting string literals. But if string contains expressions it is split into multiple tokens.
It will however succeed in parsing this:
```php
"{$a}"

```
Thanks to:
```php
if ($nextTokenType !== T_VARIABLE)
```

But anything more complex will fail, like:
```php
"{$a->b}"
```
Not to mention that one:
```php
"{$a->asd()['a'][0]}"
```

Thus counting quatation marks as a way to detect that we can be just walking string literal seems to be the way to go?

Taking this problem aside, I wonder if it wouldn't be better to just skip process of deducing begining of expressions in this scenario. Where ```FileIndexer::indexConstant``` is parsing ```$rawData['defaultValue']```. Since it already contains complete expression, deducing process should not be needed?

**Comment by Gert-dev** [comment] 2017-02-02 17:56
Thanks for the detailed explanation. I'll see if I can reproduce with a test case and then proceed to fix it.

@Talv You make a valid point regarding the indexer, as the default value for a constant or property should always be valid as a whole and is always a single expression, I'm not sure right now of why the boundary searching is still happening - perhaps I had an explicit reason for it which I can't remember, but either way I'll take a look into seeing if it can be removed. In any case, I'll look into fixing the issue regardless as no valid PHP code should be failing in the partial parser.

**Comment by Gert-dev** [comment] 2017-02-02 19:16
I've published a new release containing a fix for this, along with a new release of the base package.

Regarding the need to find the boundary for default values - it's currently using that code as default values don't parse with php-parser when things such as '<?php ' is missing as prefix and, in some cases, a semicolon. I can probably split the error correction off from the boundary determination and still skip the latter altogether though, I might look into that later.

Let me know if this fixes it for you.

**Comment by Talv** [comment] 2017-02-03 18:26
Almost there :)

Now it can't deal with additional parenthesis around the string with interpolated expressions, e.g.
```php
("$a")
```

As soon as end of quotation is reached, it thinks it is begining of expressions, thus we are left with ```"$a")```, and leading ```(``` is dropped.

**Comment by GiacoCorsiglia** [comment] 2017-02-04 17:39
Although I defer to @Talv's additional test cases, this new release has resolved the issue for my use case.  I very much appreciate the quick turnaround—and the glimpse into parser internals in this thread.

**Comment by Gert-dev** [comment] 2017-02-06 20:06
@GiacoCorsiglia Nice to hear, thanks for taking the time to report it!

@Talv I've released a new version that also adds a fix for the regression. I probably should also test cases that already work before fixing cases that don't work, as I must have regressed that one by fixing the previous one :-).

**Comment by Talv** [comment] 2017-02-07 00:26
I'm pleased to see split of PartialParser. :+1: 
Good work overall.
I got nothing more to report in scope of this issue.

**Closed** 2017-02-08 17:35 UTC
Labels: bug
